# Generated by Django 3.2.13 on 2022-07-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='/home/ttn/Desktop/onions.jpg', upload_to='uploads/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='N/A', max_length=500, null=True),
        ),
    ]
