# Generated by Django 3.2.13 on 2022-07-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220704_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='/home/ttn/Desktop/onions.jpg', upload_to='uploads/categoryimages/'),
        ),
    ]
