# Generated by Django 3.2.13 on 2022-07-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
